version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: backend
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend
